name: language_rally
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  json_annotation: ^4.10.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  uuid: ^4.5.1

  # State Management
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0

  # Internationalization
  intl: ^0.20.2

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  url_launcher: ^6.2.5
  reorderable_grid_view: ^2.2.8

  # File handling
  archive: ^3.4.0
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.5
  build_runner: ^2.4.6
  json_serializable: ^6.7.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/badges/
    - assets/images/package_icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Inter_18pt-Bold.ttf
          weight: 700

